on: push

jobs: 
  secrets:
    runs-on: ubuntu-latest
    steps: 
      - name: shell-cmd
      - run: |
          echo $MY_SECRET 
        shell: bash
        env: 
          MY_SECRET: ${{ secrets.MY_SECRET }}
    
      - name: python-cmd
      - run: |
          import os
          os.getenv("MY_SECRET")
        shell: python
        env: 
          MY_SECRET: ${{ secrets.MY_SECRET }}
